title: GH pages Playground
author: attero
email: code@attero.me
description: > # this means to ignore newlines until "show_excerpts:"
  Tesing Jekyll & gh-pages

show_excerpts: false # set to true to show excerpts on the homepage

# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
playground:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: playground

plugins:
 - jekyll-feed
 - jekyll-seo-tag
